<?php
/**
 * Created by PhpStorm.
 * User: sokool
 * Date: 02.01.15
 * Time: 13:23
 */

namespace MintSoft\FormShaper\Form\Element\Select2;

use MintSoft\FormShaper\Form\Element\Select2 as Select2Element;
use Zend\ServiceManager\ServiceLocatorInterface;

class Tag extends Select2Element
{
    protected $toggle = 'zf2-tag';

    /**
     * @var \Doctrine\ORM\EntityManager
     */
    protected $em;
    public function setServiceLocator(ServiceLocatorInterface $serviceLocator)
    {
        $this->em = $serviceLocator->getServiceLocator()->get('Doctrine\ORM\EntityManager');

        return parent::setServiceLocator($serviceLocator); // TODO: Change the autogenerated stub
    }

    public function setValue($value)
    {

        Debugger::barDump($value);
        if(is_numeric($value)) {
            $class = $this->getOption('target');
            $this->setToggleAttribute('initSelection',[
                'id' => $value,
                'text' => $this->em->getRepository($class)->findById($value)[0]->getName()
            ]);

        }



        $this->value = $value;
//        parent::setValue($value);
//        $tableManager = $this->getServiceLocator()->get('Flo\Db\TableManager');
//        $tableName    = $this->getToggleOption('table');
//        $methodName   = $this->getToggleOption('method');
//        $valuesArray  = $tableManager->get($tableName)->{$methodName}(explode(',', $value));
//        $selection    = [];
//        foreach ($valuesArray as $a) {
//            $selection[] = [
//                'id'   => $a->getId(),
//                'text' => $a->getName(),
//            ];
//        }

        $this->setToggleAttribute('initSelection', ['id' => '', 'text' => $value]);

        return $this;
    }
} 